version: "3.5"
services:
  cribl:
    image: cribl/cribl:next
    ports:
      - 9000:9000
      - 10200:10200
      - 10088:10088
      - 10080:10080
      - 10001:10001
      - 10002:10002
      - 9999:9999
      - 5140:5140
    volumes:
      - ./cribl/local:/opt/cribl/local
      - ./cribl/state:/opt/cribl/state
      - ./cribl/data:/opt/cribl/data
      - ./cribl/out:/out
  influxdb:
    image: influxdb:1.7
    environment:
      - INFLUXDB_DB=cribl
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    ports:
      - 8086:8086
    volumes:
      - influxdb:/var/lib/influxdb
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/etc/grafana/provisioning
      - grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=cribldemo
  telegraf:
    build: ./telegraf
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock
  mtr:
    build: ./mtr
    environment:
      - PING_HOST=8.8.8.8
      - OUT_HOST=cribl
      - OUT_PORT=10001
  speedtest:
    build: ./speedtest
    environment:
      - SPEEDTEST_INTERVAL_HOURS=15
      - CRIBL_TCPJSON=cribl:10001
      - OUT_HOST=cribl
      - OUT_PORT=10001
volumes:
  influxdb:
  grafana:
